"""
Donation file structure data for TikTok takeout flows

Split from entries_data.py. To regenerate, run structure/flow_generation/generate_entries.py
which will use the Merged_structures_*.csv to determine the required entries.
"""

from port.helpers.parsers import Entry, Node

TIKTOK_ENTRIES: dict[str, list[Entry]] = {
    'Activity': [
        Entry(table='Activity', filename=None, tree=Node(columns={'videosCommentedOnSinceAccountRegistration': ('Activity', 'Activity Summary', 'ActivitySummaryMap', 'videosCommentedOnSinceAccountRegistration'), 'videosSharedSinceAccountRegistration': ('Activity', 'Activity Summary', 'ActivitySummaryMap', 'videosSharedSinceAccountRegistration'), 'videosWatchedToTheEndSinceAccountRegistration': ('Activity', 'Activity Summary', 'ActivitySummaryMap', 'videosWatchedToTheEndSinceAccountRegistration')}, children={'Activity': Node(columns={}, children={'Favorite Videos': Node(columns={}, children={'FavoriteVideoList': Node(columns={'Date': ('Date',), 'Link': ('Link',)}, children={})}), 'Following List': Node(columns={}, children={'Following': Node(columns={'Date': ('Date',), 'UserName': ('UserName',)}, children={})}), 'Hashtag': Node(columns={}, children={'HashtagList': Node(columns={'HashtagName': ('HashtagName',), 'HashtagLink': ('HashtagLink',)}, children={})}), 'Like List': Node(columns={}, children={'ItemFavoriteList': Node(columns={'date': ('date',), 'link': ('link',)}, children={})}), 'Search History': Node(columns={}, children={'SearchList': Node(columns={'Date': ('Date',), 'SearchTerm': ('SearchTerm',)}, children={})}), 'Share History': Node(columns={}, children={'ShareHistoryList': Node(columns={'Date': ('Date',), 'SharedContent': ('SharedContent',), 'Link': ('Link',)}, children={})}), 'Video Browsing History': Node(columns={}, children={'VideoList': Node(columns={'Date': ('Date',), 'Link': ('Link',)}, children={})}), 'Follower List': Node(columns={}, children={'FansList': Node(columns={'Date': ('Date',), 'UserName': ('UserName',)}, children={})})})})),
    ],
    'Ads And Data': [
        Entry(table='Ads And Data', filename=None, tree=Node(columns={'AdInterestCategories': ('Ads and data', 'Ad Interests', 'AdInterestCategories')}, children={})),
    ],
    'App Settings': [
        Entry(table='App Settings', filename=None, tree=Node(columns={'App Language': ('App Settings', 'Settings', 'SettingsMap', 'App Language'), 'Filter Comments': ('App Settings', 'Settings', 'SettingsMap', 'Filter Comments'), 'Interests': ('App Settings', 'Settings', 'SettingsMap', 'Interests'), 'Private Account': ('App Settings', 'Settings', 'SettingsMap', 'Private Account'), 'Web Language': ('App Settings', 'Settings', 'SettingsMap', 'Web Language'), 'Who Can Duet With Me': ('App Settings', 'Settings', 'SettingsMap', 'Who Can Duet With Me'), 'Who Can Post Comments': ('App Settings', 'Settings', 'SettingsMap', 'Who Can Post Comments'), 'Who Can Send Me Message': ('App Settings', 'Settings', 'SettingsMap', 'Who Can Send Me Message'), 'Who Can Stitch with your videos': ('App Settings', 'Settings', 'SettingsMap', 'Who Can Stitch with your videos'), 'Who Can View Videos I Liked': ('App Settings', 'Settings', 'SettingsMap', 'Who Can View Videos I Liked'), 'Keyword filters for videos in Following feed': ('App Settings', 'Settings', 'SettingsMap', 'Content Preferences', 'Keyword filters for videos in Following feed'), 'Keyword filters for videos in For You feed': ('App Settings', 'Settings', 'SettingsMap', 'Content Preferences', 'Keyword filters for videos in For You feed'), 'Personalized Ads': ('App Settings', 'Settings', 'SettingsMap', 'Personalized Ads'), 'Allow Reuse of Content': ('App Settings', 'Settings', 'SettingsMap', 'Allow Reuse of Content')}, children={'App Settings': Node(columns={}, children={'Block': Node(columns={}, children={'BlockList': Node(columns={'Date': ('Date',), 'UserName': ('UserName',)}, children={})}), 'Block List': Node(columns={}, children={'BlockList': Node(columns={'Date': ('Date',), 'UserName': ('UserName',)}, children={})})})})),
    ],
    'Comment': [
        Entry(table='Comment', filename=None, tree=Node(columns={}, children={'Comment': Node(columns={}, children={'Comments': Node(columns={}, children={'CommentsList': Node(columns={'date': ('date',), 'comment': ('comment',), 'photo': ('photo',), 'url': ('url',)}, children={})})})})),
    ],
    'Post': [
        Entry(table='Post', filename=None, tree=Node(columns={}, children={'Post': Node(columns={}, children={'Posts': Node(columns={}, children={'VideoList': Node(columns={'Date': ('Date',), 'Link': ('Link',), 'Likes': ('Likes',), 'WhoCanView': ('WhoCanView',), 'AllowComments': ('AllowComments',), 'AllowStitches': ('AllowStitches',), 'AllowDuets': ('AllowDuets',), 'AllowStickers': ('AllowStickers',), 'AllowSharingToStory': ('AllowSharingToStory',), 'ContentDisclosure': ('ContentDisclosure',), 'AIGeneratedContent': ('AIGeneratedContent',), 'Sound': ('Sound',), 'Location': ('Location',), 'Title': ('Title',), 'AddYoursText': ('AddYoursText',)}, children={})})})})),
    ],
    'Profile': [
        Entry(table='Profile', filename=None, tree=Node(columns={'likesReceived': ('Profile', 'Profile Info', 'ProfileMap', 'likesReceived'), 'userName': ('Profile', 'Profile Info', 'ProfileMap', 'userName'), 'followerCount': ('Profile', 'Profile Info', 'ProfileMap', 'followerCount'), 'followingCount': ('Profile', 'Profile Info', 'ProfileMap', 'followingCount')}, children={})),
    ],
    'Tiktok Live': [
        Entry(table='Tiktok Live', filename=None, tree=Node(columns={'Allow agencies to find and invite you': ('Tiktok Live', 'Go Live Settings', 'SettingsMap', 'Allow agencies to find and invite you'), 'Allow others to invite you to co-host in LIVE': ('Tiktok Live', 'Go Live Settings', 'SettingsMap', 'Allow others to invite you to co-host in LIVE'), 'Allow people to send and receive comments during your LIVE': ('Tiktok Live', 'Go Live Settings', 'SettingsMap', 'Allow people to send and receive comments during your LIVE'), 'Allow suggested LIVE hosts to invite you to co-host in LIVE': ('Tiktok Live', 'Go Live Settings', 'SettingsMap', 'Allow suggested LIVE hosts to invite you to co-host in LIVE'), 'Allow viewers to request to go LIVE with you': ('Tiktok Live', 'Go Live Settings', 'SettingsMap', 'Allow viewers to request to go LIVE with you'), 'Allow viewers to see and send questions and answers in your LIVE': ('Tiktok Live', 'Go Live Settings', 'SettingsMap', 'Allow viewers to see and send questions and answers in your LIVE'), 'Allow viewers to send you gifts during your LIVE': ('Tiktok Live', 'Go Live Settings', 'SettingsMap', 'Allow viewers to send you gifts during your LIVE'), 'Hide potential spam or offensive comments from your LIVE': ('Tiktok Live', 'Go Live Settings', 'SettingsMap', 'Hide potential spam or offensive comments from your LIVE'), 'Show your username and gift information in features with ranking lists': ('Tiktok Live', 'Go Live Settings', 'SettingsMap', 'Show your username and gift information in features with ranking lists'), 'GoLiveList': ('Tiktok Live', 'Go Live History', 'GoLiveList'), 'WatchTime': ('Tiktok Live', 'Watch Live History', 'WatchLiveMap', '$NUMBER', 'WatchTime'), 'Link': ('Tiktok Live', 'Watch Live History', 'WatchLiveMap', '$NUMBER', 'Link')}, children={'Tiktok Live': Node(columns={}, children={'Go Live Settings': Node(columns={}, children={'SettingsMap': Node(columns={}, children={'Hide comments that contain the following keywords from your LIVE': Node(columns={'Hide comments that contain the following keywords from your LIVE': ()}, children={}), 'People you assigned to moderate your LIVE': Node(columns={'People you assigned to moderate your LIVE': ()}, children={})})}), 'Watch Live History': Node(columns={}, children={'WatchLiveMap': Node(columns={}, children={'$NUMBER': Node(columns={}, children={'Comments': Node(columns={'CommentTime': ('CommentTime',), 'CommentContent': ('CommentContent',), 'RawTime': ('RawTime',)}, children={})})})})})})),
    ],
    'Video': [
        Entry(table='Video', filename=None, tree=Node(columns={}, children={'Video': Node(columns={}, children={'Videos': Node(columns={}, children={'VideoList': Node(columns={'Date': ('Date',), 'Link': ('Link',), 'Likes': ('Likes',), 'WhoCanView': ('WhoCanView',), 'AllowComments': ('AllowComments',), 'AllowStitches': ('AllowStitches',), 'AllowDuets': ('AllowDuets',), 'AllowStickers': ('AllowStickers',), 'AllowSharingToStory': ('AllowSharingToStory',), 'ContentDisclosure': ('ContentDisclosure',), 'AIGeneratedContent': ('AIGeneratedContent',), 'Sound': ('Sound',), 'Location': ('Location',), 'Title': ('Title',), 'AddYoursText': ('AddYoursText',)}, children={})})})})),
    ],
    'Your Activity': [
        Entry(table='Your Activity', filename=None, tree=Node(columns={'FavoriteHashtagList': ('Your Activity', 'Favorite Hashtags', 'FavoriteHashtagList'), 'videosCommentedOnSinceAccountRegistration': ('Your Activity', 'Activity Summary', 'ActivitySummaryMap', 'videosCommentedOnSinceAccountRegistration'), 'videosSharedSinceAccountRegistration': ('Your Activity', 'Activity Summary', 'ActivitySummaryMap', 'videosSharedSinceAccountRegistration'), 'videosWatchedToTheEndSinceAccountRegistration': ('Your Activity', 'Activity Summary', 'ActivitySummaryMap', 'videosWatchedToTheEndSinceAccountRegistration')}, children={'Your Activity': Node(columns={}, children={'Searches': Node(columns={}, children={'SearchList': Node(columns={'Date': ('Date',), 'SearchTerm': ('SearchTerm',)}, children={})}), 'Watch History': Node(columns={}, children={'VideoList': Node(columns={'Date': ('Date',), 'Link': ('Link',)}, children={})}), 'Favorite Effects': Node(columns={}, children={'FavoriteEffectsList': Node(columns={'Date': ('Date',), 'EffectLink': ('EffectLink',)}, children={})}), 'Favorite Sounds': Node(columns={}, children={'FavoriteSoundList': Node(columns={'Date': ('Date',), 'Link': ('Link',)}, children={})}), 'Favorite Videos': Node(columns={}, children={'FavoriteVideoList': Node(columns={'Date': ('Date',), 'Link': ('Link',)}, children={})}), 'Follower': Node(columns={}, children={'FansList': Node(columns={'Date': ('Date',), 'UserName': ('UserName',)}, children={})}), 'Following': Node(columns={}, children={'Following': Node(columns={'Date': ('Date',), 'UserName': ('UserName',)}, children={})}), 'Hashtag': Node(columns={}, children={'HashtagList': Node(columns={'HashtagName': ('HashtagName',), 'HashtagLink': ('HashtagLink',)}, children={})}), 'Like List': Node(columns={}, children={'ItemFavoriteList': Node(columns={'date': ('date',), 'link': ('link',)}, children={})}), 'Favorite Collection': Node(columns={}, children={'FavoriteCollectionList': Node(columns={'FavoriteCollectionList': ()}, children={})}), 'Share History': Node(columns={}, children={'ShareHistoryList': Node(columns={'Date': ('Date',), 'SharedContent': ('SharedContent',), 'Link': ('Link',)}, children={})})})})),
    ],
}
